/*
 * Tasmota Device Manager API
 *
 * Device manager for Tasmota devices via MQTT [Source](https://github.com/mbezuidenhout/tdm).
 *
 * API version: 0.1.0
 * Contact: marius.bezuidenhout@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package tasmota

type ZigbeeTH01 struct {
	Device            string  `json:"Device"`
	Name              string  `json:"Name,omitempty"`
	ModelId           string  `json:"ModelId"`
	Temperature       float32 `json:"Temperature,omitempty"`
	Humidity          float32 `json:"Humidity,omitempty"`
	BatteryPercentage int     `json:"BatteryPercentage,omitempty"`
	LastSeen          int     `json:"LastSeen"`
	LastSeenEpoch     int64   `json:"LastSeenEpoch"`
	LinkQuality       int     `json:"LinkQuality"`
	Reachable         bool    `json:"Reachable"`
}
