/*
 * Tasmota Device Manager API
 *
 * Device manager for Tasmota devices via MQTT [Source](https://github.com/mbezuidenhout/tdm).
 *
 * API version: 0.1.0
 * Contact: marius.bezuidenhout@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package tasmota

import mqtt "github.com/eclipse/paho.mqtt.golang"

type Device struct {
	// Unique device topic
	Topic string `json:"Topic"`
	// Full topic format
	Fulltopic string `json:"FullTopic"`
	// Device status
	Online     bool `json:"Online"`
	mqttClient mqtt.Client
	UptimeSec  uint    `json:"UptimeSec,omitempty"`
	LoadAvg    uint    `json:"LoadAvg,omitempty"`
	Timezone   string  `json:"Timezone,omitempty"`
	Network    Network `json:"StatusNET,omitempty"`
}
