/*
 * Tasmota Device Manager API
 *
 * Device manager for Tasmota devices via MQTT [Source](https://github.com/mbezuidenhout/tdm).
 *
 * API version: 0.1.0
 * Contact: marius.bezuidenhout@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package tasmota

type Wifi struct {
	SSId    string `json:"SSId"`
	BSSId   string `json:"BSSId"`
	Channel int    `json:"Channel"`
	Mode    string `json:"Mode"`
	Signal  int    `json:"Signal"`
}
